<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-27T15:44:20 IST" name="Default suite" finished-at="2023-12-27T15:45:18 IST" duration-ms="57793">
    <groups>
    </groups>
    <test started-at="2023-12-27T15:44:20 IST" name="Default test" finished-at="2023-12-27T15:45:18 IST" duration-ms="57793">
      <class name="com.fa.clp.testcases.PolicyNumber">
        <test-method is-config="true" signature="onStartGo()[pri:0, instance:com.fa.clp.testcases.PolicyNumber@4b7dc788]" started-at="2023-12-27T15:44:20 IST" name="onStartGo" finished-at="2023-12-27T15:44:23 IST" duration-ms="2827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onStartGo -->
        <test-method signature="policyNumber()[pri:0, instance:com.fa.clp.testcases.PolicyNumber@4b7dc788]" started-at="2023-12-27T15:44:23 IST" name="policyNumber" finished-at="2023-12-27T15:45:17 IST" duration-ms="54714" status="FAIL">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot run program "C:\Users\Fasoftwares\Desktop\code.txt": CreateProcess error=193, %1 is not a valid Win32 application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot run program "C:\Users\Fasoftwares\Desktop\code.txt": CreateProcess error=193, %1 is not a valid Win32 application
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at java.base/java.lang.Runtime.exec(Runtime.java:418)
at java.base/java.lang.Runtime.exec(Runtime.java:315)
at com.fa.clp.abstractcomponents.AbstractComponents.uploadingFileInWindowsUsingAutoIt(AbstractComponents.java:149)
at com.fa.clp.pageobject.DocumentUploadPage.uploadingDocument(DocumentUploadPage.java:79)
at com.fa.clp.testcases.PolicyNumber.policyNumber(PolicyNumber.java:153)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- policyNumber -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.fa.clp.testcases.PolicyNumber@4b7dc788]" started-at="2023-12-27T15:45:17 IST" name="tearDown" finished-at="2023-12-27T15:45:18 IST" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.fa.clp.testcases.PolicyNumber -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
